Python/ThinkLog/app/models.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com
# models.py

from flask_sqlalchemy import SQLAlchemy
import pymongo as pm
db = SQLAlchemy()


class MongoDB:
    def __init__(self, db_config=None):
        if db_config:
            self.client = pm.MongoClient(db_config['HOST'], db_config['PORT'])
        else:
            self.client = pm.MongoClient('localhost', 27017)

    def __del__(self):
        self.client.close()

Python/ThinkLog/app/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com
import os
from werkzeug.utils import import_string
from flask import Flask
ROOT_PATH = os.path.abspath(os.path.dirname(__file__))
from app.config.config import DB, BLUEPRINTS
import app.main


class App():
    def __init__(self):
        self.app = Flask(__name__)
        self.app.config.from_object(app.config.config)
        self.db = DB
        self.create_blueprints(BLUEPRINTS)
        self.db.init_app(self.app)

    def create_blueprints(self, blueprints):
        for bp in blueprints:
            self.app.register_blueprint(
                import_string(bp['url']), url_prefix=bp['url_prefix'])

Python/ThinkLog/app/config/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com

Python/ThinkLog/app/main/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com

from flask import Blueprint
main = Blueprint('main', __name__)
from .views import index

Python/ThinkLog/app/main/common/__init__.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com

Python/ThinkLog/app/main/views/index.py
#-------------------------------------------------------------------------------
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author:      jianwen
# Email:       npujianwenxu@163.com
# main index
#-------------------------------------------------------------------------------
import os
import json
from flask import render_template, request, jsonify
from werkzeug.utils import secure_filename
from app.config.config import MONGODB, UPLOAD_PATH, LOG_TYPE
from ..common.public import has_log_for_current_ip, get_log_tables_type, file_is_allowed, save_data_to_db
from .. import main


@main.route('/')
def index():
    db_name = 'log_' + str(request.remote_addr).replace('.', '_')
    tables = MONGODB.client[db_name].list_collection_names()
    log = get_log_tables_type(tables)
    return render_template(
        'main/index.html',
        user_ip=request.remote_addr,
        log_type=LOG_TYPE,
        log=log,
        user_has_logs=has_log_for_current_ip(db_name))


@main.route('/upload/', methods=['POST'])
def upload_file():
    db_name = 'log_' + str(request.remote_addr).replace('.', '_')
    if request.method == 'POST':
        if 'file' not in request.files:
            return 'No file part'
        file = request.files['file']
        log_type = request.form['log_type']

        if file.filename == '':
            return 'No selected file'
        if file_is_allowed(file.filename):
            if file:
                save_floder = UPLOAD_PATH + '/' + str(
                    request.remote_addr) + '/' + str(log_type) + '/'
                if not os.path.exists(save_floder):
                    os.makedirs(save_floder)
                save_path = save_floder + secure_filename(file.filename)
                try:
                    file.save(save_path)
                    save_data_to_db(save_path, log_type, db_name)
                except:
                    return 'file is upload but error occure when saving file for unknow reason'
                return 'file upload successed'
        else:
            return 'file type is not support'
    return 'file upload fialed'


@main.route('/show/<db_table>')
def show(db_table):
    datas = {}
    db_name = 'log_' + str(request.remote_addr).replace('.', '_')
    mdb = MONGODB.client[db_name]
    log = mdb[db_table]

    cursor = log.find({}, {'_id': 0})  #.limit(50)

    datas['total'] = cursor.count()
    datas['rows'] = list(cursor)
    items = list(datas['rows'][0].keys())
    titles = []
    selections = []
    for item in items:
        titles.append({'field': item, 'title': item, 'width': 100})
        selections.append({'id': item, 'text': item})
    datas['title'] = titles
    datas['selections'] = selections
    return jsonify(datas)


@main.route('/plot/', methods=['POST'])
def plot():
    if request.method == 'POST':
        json_data = json.loads(request.get_data().decode("utf-8"))
        print(json_data)
        return "OK"

Python/ThinkLog/app/templates/main/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>LOG在线透视</title>
    <link rel="stylesheet" type="text/css" href={{url_for('static', filename='easyui/themes/default/easyui.css')}}>
    <link rel="stylesheet" type="text/css" href={{url_for('static', filename='easyui/themes/icon.css')}}>
    <script type="text/javascript" src={{url_for('static', filename='easyui/jquery.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='easyui/jquery.easyui.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='easyui/datagrid-bufferview.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='easyui/datagrid-filter.js')}}></script>
</head>

<body class="easyui-layout">
    <div data-options="region:'north',border:false" style="height:45px;background:#B3DFDA;padding:10px">
        Log在线透视系统
    </div>
    <div data-options="region:'west',split:true,title:'Log'" style="width:150px;padding:10px;">

        <ul class="easyui-tree">
            <li>
                <span>IP:{{user_ip}}</span>
                <ul>
                    {% if user_has_logs %}
                    {% for key,values in log.items() %}
                    <li data-options="state:'closed'">
                        <span>{{key}}</span>
                        <ul>
                            {% for v in values%}
                            <li>
                                <a href="javascript:void(0)" onclick="show('{{v}}')"">{{v}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                    {% endif %}
                    <li>
                        <a href="
                                    javascript:void(0)" onclick="$('#dlg').dialog('open')">Log加载</a>
                            </li>
                        </ul>
                    </li>
                </ul>
    </div>
    <div data-options="region:'east',split:true,collapsed:false,title:'透视选项'" style="width:200px;padding:10px;">
        <p>筛选器</p>
        <select id="data_filter" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%">
        </select>
        <p>列</p>
        <select id="data_column" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%">
        </select>
        <p>行</p>
        <select id="data_row" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%">
        </select>
        <p>值</p>
        <select id="data_value" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%">
        </select>
        <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-save'" onclick="plot()">GetValue</a>
    </div>
    {% if user_has_logs%}
    <div id="dlg" class="easyui-dialog" title="Log加载" data-options="closed:true" style="width:40%;height:200px;padding:10px">
        <form id="uploadForm" enctype="multipart/form-data">
            <div>
                <select id="log_type" class="easyui-combobox" name="log_type" style="width:30%;">
                    <option value="0">选择Log类型</option>
                    {% for type in log_type %}
                    <option value="{{type.key}}">{{type.value}}</option>
                    {% endfor %}
                </select>
                <input id="log_file" class="easyui-filebox" name="file" style="width:69%" data-options="prompt:'仅支持CVS文件'">
            </div>
            <div>
                <a href="#" class="easyui-linkbutton" style="width:100%;margin-top:20px" onclick="upload()">Upload</a>
            </div>
            <div id="p" class="easyui-progressbar" style="width:100%;;margin-top:20px"></div>
        </form>
    </div>
    {% else %}
    <div id="dlg" class="easyui-dialog" title="Log加载" data-options="closed:false" style="width:40%;height:200px;padding:10px">
        <form id="uploadForm" enctype="multipart/form-data">

            <div>
                <select id="log_type" class="easyui-combobox" name="log_type" style="width:30%;">
                    <option value="0">选择Log类型</option>
                    {% for type in log_type %}
                    <option value="{{type.key}}">{{type.value}}</option>
                    {% endfor %}
                </select>
                <input id="log_file" class="easyui-filebox" name="file" style="width:69%" data-options="prompt:'仅支持CVS文件'">
            </div>
            <div>
                <a href="#" class="easyui-linkbutton" style="width:100%;margin-top:20px" onclick="upload()">Upload</a>
            </div>
            <div id="p" class="easyui-progressbar" style="width:100%;;margin-top:20px"></div>
        </form>
    </div>
    {% endif %}
    <div id="content" data-options=" region:'center',title:'Log数据'">
        {% if user_has_logs%}
        <table id="log_table" style="width:99.9%;height:100%" data-options="view:bufferview,rownumbers:true,singleSelect:false,autoRowHeight:false">
            <thead>
                <tr></tr>
            </thead>
        </table>
        {% endif %}
    </div>
</body>
<script>
    function upload() {
        var formData = new FormData($('#uploadForm')[0]);
        if ($('#log_type').combobox('getValues') != 0) {
            if ($('#log_file').filebox('getValue').length > 0) {
                $.ajax(
                    {
                        url: "{{ url_for('main.upload_file')}}",
                        type: "POST",
                        data: formData,
                        async: true,
                        cashe: false,
                        contentType: false,
                        processData: false,
                        xhr: function () {
                            myXhr = $.ajaxSettings.xhr();
                            if (myXhr.upload) {
                                myXhr.upload.addEventListener('progress', function (e) {
                                    var per = Math.floor(100 * e.loaded / e.total);
                                    $('#p').progressbar('setValue', per);
                                }, false);
                            }
                            return myXhr;
                        },
                        success: function (returndata) {
                            $.messager.alert('Log加载', returndata);
                            $('#log_file').filebox('setValue', " ");
                            $('#dlg').dialog('close');
                        },
                        error: function (returndata) {
                            $.messager.alert('Log加载', returndata);
                            $('#log_file').filebox('setValue', " ");
                            $('#dlg').dialog('close');
                        },
                    },

                );
            }
            else {
                $.messager.alert('Log加载', "请选择log文件");
            }
        }
        else {
            $.messager.alert('Log加载', "请选择log类型");
        }

    }
</script>

<script>
    function ajaxLoading() {
        $("<div class=\"datagrid-mask\"></div>").css({ display: "block", width: "100%", height: $(window).height() }).appendTo("body");
        $("<div class=\"datagrid-mask-msg\"></div>").html("数据加载中，请稍候...").appendTo("body").css({ display: "block", left: ($(document.body).outerWidth(true) - 190) / 2, top: ($(window).height() - 45) / 2 });
    }
</script>
<script>
    function ajaxLoadEnd() {
        $(".datagrid-mask").remove();
        $(".datagrid-mask-msg").remove();
    }
</script>
<script type="text/javascript">
    function show(para) {
        //动态加载标题和数据
        //fLoadTable();
        $.ajax({
            url: "/home/show/" + para,
            type: "get",
            dataType: "json",
            beforeSend: ajaxLoading,
            success: function (data) {
                $("#log_table").datagrid({
                    columns: [data.title]    //动态取标题
                });
                $("#log_table").datagrid("loadData", data.rows);  //动态取数据

                var datas = [];
                $("#data_filter").combobox('clear');
                $("#data_column").combobox('clear');
                $("#data_row").combobox('clear');
                $("#data_value").combobox('clear');

                for (var i = 0; i < data.selections.length; i++) {
                    var value = data.selections[i].id;
                    var text = data.selections[i].text;
                    datas.push({ "text": text, "value": value });
                }
                $("#data_filter").combobox("loadData", datas);
                $("#data_column").combobox("loadData", datas);
                $("#data_row").combobox("loadData", datas);
                $("#data_value").combobox("loadData", datas);

                ajaxLoadEnd();

            }
        });
    }
</script>
<script>
    function plot() {
        $.ajax(
            {
                type: 'POST',
                url: '/home/plot/',
                data: JSON.stringify({
                    "data_filter": $('#data_filter').combobox('getValues'),
                    "data_column": $('#data_column').combobox('getValues'),
                    "data_row": $('#data_row').combobox('getValues'),
                    "data_value": $('#data_value').combobox('getValues')
                }),
                success: function (data) {
                    alert(data);
                },
                error: function (data) {
                    alert(data);
                },
            }
        );
    }
</script>

</html>

Python/ThinkLog/app/templates/main/test.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Basic Layout - jQuery EasyUI Demo</title>
    <link rel="stylesheet" type="text/css" href={{url_for('static', filename='easyui/themes/default/easyui.css')}}>
    <link rel="stylesheet" type="text/css" href={{url_for('static', filename='easyui/themes/icon.css')}}>
    <script type="text/javascript" src={{url_for('static', filename='easyui/jquery.min.js')}}></script>
    <script type="text/javascript" src={{url_for('static', filename='easyui/jquery.easyui.min.js')}}></script>
</head>

<body class="easyui-layout">

    <table id="dg" class="easyui-datagrid" style="width:99.9%;height:58%" iconCls="icon-save" rownumbers="true"
        pagination="true" data-options="
rownumbers:true,
singleSelect:true,
autoRowHeight:false,
pagination:true">
        <thead>
            <tr></tr>
        </thead>
    </table>


</body>

<script type="text/javascript">
    $(function () {
        //动态加载标题和数据
        //fLoadTable();
        $.ajax({
            url: "/test/",
            type: "get",
            dataType: "json",
            success: function (data) {
                $("#dg").datagrid({
                    columns: [data.title]    //动态取标题
                });

                $("#dg").datagrid("loadData", data.rows);  //动态取数据
            }
        });
    });
</script>

</html>