Python/pms/app/urls.py
from django.urls import path,include

urlpatterns = [
    path('',include('pms.urls'))
]

Python/pms/pms/admin/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:28:07

@author: jianwen

'''



from django.urls import path

from .views import index

urlpatterns = [
    path('', index.index, name='index'),
]

Python/pms/pms/home/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:28:07

@author: jianwen

'''

from django.urls import path

from .views import index

app_name = 'home'
urlpatterns = [
    path(r'', index.index, name='index'),
    path(r'detial/<int:requirement_id>', index.detial, name='detial'),
]

Python/pms/pms/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:17:40

@author: jianwen

'''

from django.urls import path,include

urlpatterns = [
    path('', include('pms.home.urls')),
    path('admin/', include('pms.admin.urls')),
]

Python/pms/pms/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:17:40

@author: jianwen

'''

Python/pms/pms/admin/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:25:50

@author: jianwen

'''

from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the admin index.")

Python/pms/pms/home/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

Created on 2018-12-29 20:26:26

@author: jianwen

'''

from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

def detial(request, requirement_id):
    return render(request, 'home/detial.html')

Python/pms/templates/home/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>过程管理系统</title>
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="{% static 'easyui/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'easyui/themes/icon.css' %}">
    <script type="text/javascript" src="{% static 'easyui/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'easyui/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'easyui/datagrid-bufferview.js' %}"></script>
    <script type="text/javascript" src="{% static 'easyui/datagrid-filter.js' %}"></script>
    <style type="text/css">
        *{font-size:12px; font-family:Tahoma,Verdana,微软雅黑,新宋体}
        
        .accordion .accordion-header-selected {
                background:rgb(231, 240, 255)
                }
        .tree-node-selected{
            background:rgb(231, 240, 255)
        }
        a{color:Black; text-decoration:none;}
        a:link,a:visited{
         text-decoration:none;  
         color:rgb(12, 12, 12);
         
        }
    </style>

</head>

<body class="easyui-layout" >
    {% block top %}     
    {% endblock %}

    {% block left_menu %}  
    {% endblock%}

    {% block center %}
    {% endblock%} 

    {% block right %}
    {% endblock%}

</body>

</html>

Python/pms/templates/home/detial.html
{% extends "home/base.html" %}

{% block center %}
<div id="content" data-options=" region:'center'"></div>
    <table class="easyui-datagrid" title="DataGrid"  style="width:100%;height:250px"
    data-options="singleSelect:true,collapsible:true,method:'get'">
        <thead>
            <tr>
                <th data-options="field:'itemid',width:80">Item ID</th>
                <th data-options="field:'productid',width:100">Product</th>
                <th data-options="field:'listprice',width:80,align:'right'">List Price</th>
                <th data-options="field:'unitcost',width:80,align:'right'">Unit Cost</th>
                <th data-options="field:'attr1',width:250">Attribute</th>
                <th data-options="field:'status',width:60,align:'center'">Status</th>
            </tr>
        </thead>
    </table>

    <table id="dg" class="easyui-datagrid" title="Fluid DataGrid" style="width:100%;height:250px"
			data-options="singleSelect:true,collapsible:true,method:'get'">
		<thead>
			<tr>
				<th data-options="field:'itemid',resizable:false" width="15%">Item ID(15%)</th>
				<th data-options="field:'productid',resizable:false" width="15%">Product(15%)</th>
				<th data-options="field:'listprice',align:'right',resizable:false" width="15%">List Price(15%)</th>
				<th data-options="field:'unitcost',align:'right',resizable:false" width="15%">Unit Cost(15%)</th>
				<th data-options="field:'attr1',resizable:false" width="25%">Attribute(25%)</th>
				<th data-options="field:'status',align:'center',resizable:false" width="15%">Status(15%)</th>
			</tr>
		</thead>
    </table>
    
</div>
{% endblock%}

Python/pms/templates/home/index.html
{% extends "home/base.html" %}
{% load staticfiles %}
{% block top %}
    <div data-options="region:'north',border:false" style="height:38px;background: #7f99be;padding:6px;" >
        <span style="float:right; padding-right:20px;color: #fff; font-family: Verdana, 微软雅黑,黑体"" class="head">欢迎 xxx<a href="#" id="editpass"  style="color: #fff; font-family: Verdana, 微软雅黑,黑体"> 修改密码</a> <a href="#" id="loginOut" style="color: #fff; font-family: Verdana, 微软雅黑,黑体">安全退出</a></span>

<span style="padding-left:10px; font-size: 18px; color: #fff; font-family: Verdana, 微软雅黑,黑体"><img src="{% static 'images/icon.png' %}" width="20" height="20" align="absmiddle"/>PMS管理系统</span>
    </div>
    
{% endblock %}

{% block left_menu %}
    <div data-options="region:'west',split:true,title:'系统菜单'" style="width:250px;">
        <div id="accordion" class="easyui-accordion" data-options="fillSpace:true,fit: true,border: false,animate: true,selected:false">
                <div title="需求管理" data-options="iconCls:'icon-requirement'">
                        <ul class="easyui-tree">
                                <li data-options="iconCls:'icon-man',state:'closed'">
                                    <span >工程过程</span>
                                    <ul>
                                        <li data-options="iconCls:'icon-add',state:'closed'">
                                            <span>需求过程</span>
                                            <ul>                          
                                                <li>
                                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>XXX需求过程</span></a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                        </ul>   
                </div>
                <div title="过程管理" data-options="iconCls:'icon-department'">
                        <ul class="easyui-tree">
                                <li data-options="iconCls:'icon-man',state:'closed'">
                                    <span >工程过程</span>
                                    <ul>
                                        <li data-options="iconCls:'icon-add',state:'closed'">
                                            <span>需求过程</span>
                                            <ul>                          
                                                <li>
                                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>XXX需求过程</span></a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                        </ul>   
                </div>
                <div title="系统管理" data-options="iconCls:'icon-sys'">
                        <ul class="easyui-tree">
                            <li data-options="iconCls:'icon-user'">
                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>&nbsp;</span> <span>用户管理</span></a>
                            </li>
                            <li data-options="iconCls:'icon-role'">
                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>&nbsp;</span><span>角色管理</span></a>
                            </li>
                            <li data-options="iconCls:'icon-hammer'">
                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>&nbsp;</span><span>权限管理</span></a>
                            </li>
                            <li data-options="iconCls:'icon-log'">
                                    <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>&nbsp;</span><span>系统日志</span></a>
                            </li>
                        </ul>   
                </div>
               
                
            </div>
    </div>
{% endblock%}
    
{% block center %}
    <div id="content" data-options=" region:'center',title:'状态栏'">
            <iframe name="mainFrame" scrolling="auto" frameborder="0" style="width:100%">
            </iframe>
    </div>
{% endblock%}

Python/pms/templates/home/test.html
{% extends "base.html" %}


{% block top %}
<div data-options="region:'north',border:false" style="height:45px;background:#B3DFDA;padding:10px">
        PMS过程管理系统
</div>
{% endblock %}

<body class="easyui-layout">
    
    <div data-options="region:'west',split:true,title:'过程管理'" style="width:250px;padding:10px;">
        <ul class="easyui-tree">
            <li>
                <span>工程过程</span>
                <ul>
                    <li data-options="state:'closed'">
                        <span>需求过程</span>
                        <ul>                          
                            <li>
                                <a href="{% url 'home:detial' 2015201893 %}" target="mainFrame"><span>XXX需求过程</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <span>建模过程</span>
                <ul>
                    <li data-options="state:'closed'">
                        <span>分析过程</span>
                        <ul>                          
                            <li>
                                <span>XXX分析过程</span>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- <div data-options="region:'east',split:true,collapsed:false,title:'透视选项'" style="width:200px;padding:10px;"> -->
        <!-- <p>筛选器</p> -->
        <!-- <select id="data_filter" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%"> -->
        <!-- </select> -->
        <!-- <p>列</p> -->
        <!-- <select id="data_column" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%"> -->
        <!-- </select> -->
        <!-- <p>行</p> -->
        <!-- <select id="data_row" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%"> -->
        <!-- </select> -->
        <!-- <p>值</p> -->
        <!-- <select id="data_value" class="easyui-combobox" name="state" data-options="multiple:true,multiline:true" style="width:98%;height:15%"> -->
        <!-- </select> -->
        <!-- <a href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-save'" onclick="plot()">GetValue</a> -->
    <!-- </div> -->
    {% if user_has_logs%}
    <div id="dlg" class="easyui-dialog" title="Log加载" data-options="closed:true" style="width:40%;height:200px;padding:10px">
        <form id="uploadForm" enctype="multipart/form-data">
            <div>
                <select id="log_type" class="easyui-combobox" name="log_type" style="width:30%;">
                    <option value="0">选择Log类型</option>
                    {% for type in log_type %}
                    <option value="{{type.key}}">{{type.value}}</option>
                    {% endfor %}
                </select>
                <input id="log_file" class="easyui-filebox" name="file" style="width:69%" data-options="prompt:'仅支持CVS文件'">
            </div>
            <div>
                <a href="#" class="easyui-linkbutton" style="width:100%;margin-top:20px" onclick="upload()">Upload</a>
            </div>
            <div id="p" class="easyui-progressbar" style="width:100%;;margin-top:20px"></div>
        </form>
    </div>
    {% else %}
    <!-- <div id="dlg" class="easyui-dialog" title="Log加载" data-options="closed:false" style="width:40%;height:200px;padding:10px"> -->
        <!-- <form id="uploadForm" enctype="multipart/form-data"> -->

            <!-- <div> -->
                <!-- <select id="log_type" class="easyui-combobox" name="log_type" style="width:30%;"> -->
                    <!-- <option value="0">选择Log类型</option> -->
                    <!-- {% for type in log_type %} -->
                    <!-- <option value="{{type.key}}">{{type.value}}</option> -->
                    <!-- {% endfor %} -->
                <!-- </select> -->
                <!-- <input id="log_file" class="easyui-filebox" name="file" style="width:69%" data-options="prompt:'仅支持CVS文件'"> -->
            <!-- </div> -->
            <!-- <div> -->
                <!-- <a href="#" class="easyui-linkbutton" style="width:100%;margin-top:20px" onclick="upload()">Upload</a> -->
            <!-- </div> -->
            <!-- <div id="p" class="easyui-progressbar" style="width:100%;;margin-top:20px"></div> -->
        <!-- </form> -->
    <!-- </div> -->
    {% endif %}
    
    <div id="content" data-options=" region:'center',title:'过程可视化'">
        <iframe name="mainFrame" scrolling="auto" frameborder="0" >
                {% if user_has_logs%}
                <table id="log_table" style="width:99.9%;height:100%" data-options="view:bufferview,rownumbers:true,singleSelect:false,autoRowHeight:false">
                    <thead>
                        <tr></tr>
                    </thead>
                </table>
                {% endif %}
        </iframe>
    </div>
</body>
<script>
    function upload() {
        var formData = new FormData($('#uploadForm')[0]);
        if ($('#log_type').combobox('getValues') != 0) {
            if ($('#log_file').filebox('getValue').length > 0) {
                $.ajax(
                    {
                        url: "",
                        type: "POST",
                        data: formData,
                        async: true,
                        cashe: false,
                        contentType: false,
                        processData: false,
                        xhr: function () {
                            myXhr = $.ajaxSettings.xhr();
                            if (myXhr.upload) {
                                myXhr.upload.addEventListener('progress', function (e) {
                                    var per = Math.floor(100 * e.loaded / e.total);
                                    $('#p').progressbar('setValue', per);
                                }, false);
                            }
                            return myXhr;
                        },
                        success: function (returndata) {
                            $.messager.alert('Log加载', returndata);
                            $('#log_file').filebox('setValue', " ");
                            $('#dlg').dialog('close');
                        },
                        error: function (returndata) {
                            $.messager.alert('Log加载', returndata);
                            $('#log_file').filebox('setValue', " ");
                            $('#dlg').dialog('close');
                        },
                    },

                );
            }
            else {
                $.messager.alert('Log加载', "请选择log文件");
            }
        }
        else {
            $.messager.alert('Log加载', "请选择log类型");
        }

    }
</script>

<script>
    function ajaxLoading() {
        $("<div class=\"datagrid-mask\"></div>").css({ display: "block", width: "100%", height: $(window).height() }).appendTo("body");
        $("<div class=\"datagrid-mask-msg\"></div>").html("数据加载中，请稍候...").appendTo("body").css({ display: "block", left: ($(document.body).outerWidth(true) - 190) / 2, top: ($(window).height() - 45) / 2 });
    }
</script>
<script>
    function ajaxLoadEnd() {
        $(".datagrid-mask").remove();
        $(".datagrid-mask-msg").remove();
    }
</script>
<script type="text/javascript">
    function show(para) {
        //动态加载标题和数据
        //fLoadTable();
        $.ajax({
            url: "/home/show/" + para,
            type: "get",
            dataType: "json",
            beforeSend: ajaxLoading,
            success: function (data) {
                $("#log_table").datagrid({
                    columns: [data.title]    //动态取标题
                });
                $("#log_table").datagrid("loadData", data.rows);  //动态取数据

                var datas = [];
                $("#data_filter").combobox('clear');
                $("#data_column").combobox('clear');
                $("#data_row").combobox('clear');
                $("#data_value").combobox('clear');

                for (var i = 0; i < data.selections.length; i++) {
                    var value = data.selections[i].id;
                    var text = data.selections[i].text;
                    datas.push({ "text": text, "value": value });
                }
                $("#data_filter").combobox("loadData", datas);
                $("#data_column").combobox("loadData", datas);
                $("#data_row").combobox("loadData", datas);
                $("#data_value").combobox("loadData", datas);

                ajaxLoadEnd();

            }
        });
    }
</script>
<script>
    function plot() {
        $.ajax(
            {
                type: 'POST',
                url: '/home/plot/',
                data: JSON.stringify({
                    "data_filter": $('#data_filter').combobox('getValues'),
                    "data_column": $('#data_column').combobox('getValues'),
                    "data_row": $('#data_row').combobox('getValues'),
                    "data_value": $('#data_value').combobox('getValues')
                }),
                success: function (data) {
                    alert(data);
                },
                error: function (data) {
                    alert(data);
                },
            }
        );
    }
</script>

</html>